name: KCBS blog
description: KCBS's fun blog

paginate: 10
markdown: redcarpet
permalink: pretty
highlighter: pygments

gems:
- jekyll-seo-tags
- jekyll-sitemap
- jekyll-mentions
- jekyll-redirect-from
