name: KCBS blog
description: KCBS's fun blog

remote_theme: mmistakes/minimal-mistakes

paginate: 10
markdown: kramdown
permalink: pretty
highlighter: rouge

gems:
- jekyll-seo-tags
- jekyll-sitemap
- jekyll-mentions
- jekyll-redirect-from
